name: hello with inputs

on:
  workflow_dispatch:
    inputs:
      greeting_name:
        description: 'Who do you want to say hi to?'
        required: true
        default: 'World'

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: greet user
        run: echo "hi ${{ github.event.inputs.greeting_name }}"
